# Mini-Project 2 
## Multi-Class Logistic Regression and Gradient Descent

Jiahua Liang   260711529    
Irene Huang    260740689 \
Tracy Zhou  


In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Data Preprocessing

In [8]:
from sklearn.datasets import load_digits 
digits = load_digits() 
print(digits.data)
print(digits.data.shape)
print(digits.target)
print(len(digits.target))
# Check nan 
print(np.isnan(digits.data).any())
# One-hot encoding 
# TODO: K-Fold cross validation 


[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797, 64)
[0 1 2 ... 8 9 8]
1797
False


In [ ]:
# Dataset 2: Vehicle https://www.openml.org/d/54

# upload csv

# Convert to pandas 
df = dataFrame(... )

# Convert from pandas to numpy 
array = df.values 

# one-hot encoding for labels 
data = array[:, 0:-2]
target = one_hot_encoding(array[:,-1])

# Check nan 


## Batch Function 
Define the batch size and split the training data

## Gradient Descent

In [ ]:
class GradientDescent: 
    # TODO: add validation set here 
    def __init__(self, lr, max_iter, epsilon, beta, batch_size, recording_history=False):
        self.lr = lr
        # 
        
        
    def run(self, gradient_fn, mini_batches, w):
        # Step 1: Split into mini-batch 
            # Shuffle data 
            # Split into mini-batch and their corresponding y
            # mini_batches = [mini_batch1, mini_batch2, ....]
            # mini_ys = [mini_y1, mini_y2,....]
    
        while # < max_iter and ....:
            for mini_batch in mini_batches: 
                #TODO: find mini_y in mini_ys
                
                # Step 2: Calculate Gradient
                grad = gradient_fn(mini_batch, mini_y, w)  # softmax_cost_fn

                # Step 3: Update W using momentum 
                self.w = ...
                
                # Step 4: Calculate training & validation set accuracy using self.w
                    # TODO: Termination Condition 
                
                
        
        return w

## Softmax Function

In [ ]:
def softmax(x, w):
    z = np.dot(x,w)
    z -= np.max(z)
    prob = (np.exp(z).T / np.sum(np.exp(z), axis=1)).T
    return prob

## Cost Function

In [ ]:
def cost_softmax_fn(x, y, w):
    
    
    return grad

## Multi-class Logistic Regression 


In [ ]:
class Logistic_Regression:
    def __init__(self, add_bias=True):
        self.add_bias = add_bias 
    
    def fit(self, x, y, optimizer):
        if x.ndim == 1:
            x = x[:, None]
        if self.add_bias:
            N = x.shape[0]
            x = np.column_stack([x, np.ones[N]])
                  
        w0 = np.zeros(D)
        self.w = optimzer.run(cost_softmax_fn, x, y, w0)
        return self


    def predict(self, x):
        if x.ndim == 1:
            x = x[:, None]
        Np = x.shape[0]
        if self.add_bias: 
            x = np.column_stack([x, np.ones(Np)])
            
        # Softmax 
        yh = softmax(x, self.w)
        # TODO: argmax...  result: yh = [0 0 1 0 0], [0 1 0 0 0]
        
        return yh 
        
        

## Training and Testing 

In [ ]:
def get_accuracy(): 
    return accuracy 


# Hyperparameters 
batch_size = 16
learning_rate = 0.01 
max_iter = 1000
epsilon = 0.08
# TODO: Grid Search -> find the best one  
# TODO: Run time 
# Need a for loop 

optimizer = GradientDescent(learning_rate, max_iter, epsilon, beta, batch_size, True)
model = Logistic_Regression()
# ! CHECK training & label name 
model.fit(x, y, optimzer)

# TODO: Plot hyperparameters vs accuracy 
